### PR TITLE
Add better defaults for `TestQuery`'s return value type

### LINKED ISSUE #9: Add better defaults for `TestQuery`'s return value type
Currently, calling `query` or `mutation` is a bit tedious as it requires to define precisely their return value. For example:

```typescript
// Typing the resulting data
const { data } = await query<{ data: User[] }>(USERS);

// Typing errors
const { errors } = await query<{ errors: ApolloError[] }>(USERS);
```

Adding the `data` property and having to mock `errors` is redundant. It can be simplified by using `graphql`'s `ExecutionResult`. The above example could be turned into:

```typescript
// Typing the resulting data
const { data } = await query<ExecutionResult<User[]>>(USERS);

// Typing errors
const { errors } = await query<ExecutionResult>(USERS);
```

I think it would be ideal if `TestQuery` could use `ExecutionResult` so we'd end up with:

```typescript
// Typing the resulting data
const { data } = await query<User[]>(USERS);

// Typing errors
const { errors } = await query(USERS);
```

I would be happy to submit a PR if that's something you would consider. I might miss some use cases so let me know what you think.

### PR DESCRIPTION
**Pull request by Zhouzi**
This PR adds tests (albeit pretty simple) and improves `TestQuery`'s return value type.

Prior to this PR, here's how a query's return value is typed:

```typescript
const { data, errors } = await query<{ data: { books: Book[] }, errors: ApolloError[] }>(GET_BOOKS);
```

Here's how it can be done with this PR:

```typescript
const { data, errors } = await query<{ books: Book[] }>(GET_BOOKS);
```

It would be a breaking change though, as with those changes, the first example's return value would end up being typed as:

```
{
  data: {
    data: {
      books: Book[]
    },
    errors: ApolloError[]
  },
  errors: ApolloError[]
}
```

I will be testing this PR on our codebase to make sure it's working as expected.

Closes #9

### CODE REVIEW

**Comment by Zhouzi** [comment]
Sorry for the delay, I had to move onto something else. I needed this recently so I fixed a few things and published it under [@zhouzi/apollo-server-integration-testing](https://www.npmjs.com/package/@zhouzi/apollo-server-integration-testing) in order to test it properly on the codebase I am working on. Type checks started failing after upgrading, as expected. But [once fixed](https://github.com/MTES-MCT/trackdechets/pull/810/commits/4291195c263077b683dc8907da52547331dd5e98) it works like a charm ✨ We are using `graphql-codegen` so here's an example of how it changed:

```typescript
// before: no type check at all
const { data } = await query(GET_USER, { variables: { id: "some_id" } })

// data is properly typechecked, along with the variables
const { data } = await query<Pick<Query, "user">, QueryUserArgs>(GET_USER, { variables: { id: "some_id" } });
```

As mentioned previously, the type change is "breaking" in the sense that it requires users of the library to update their code if they are using TypeScript.

**Comment by vitorbal** [comment]
Hi @Zhouzi thanks for the update and for looping back to this one. I'd be happy to get this merged, but I think it should be a major version bump since it will be a breaking change for typescript users. What do you think?

**Comment by Zhouzi** [comment]
Agreed, it should definitely be a major version 👍 I added it to the change log's vNext, let me know if there's anything else I can do to help.

**Comment by vitorbal** [comment]
Great, thanks again @Zhouzi! I have some pending work stuff to do today but I'll try to cut the major version later in the evening 👍

**Comment by JeremyKirkham** [comment]
Looking forward to this 👍

**Comment by vitorbal** [comment]
Just published 3.0.0 with this change! Please let me know if you find any bugs. Thanks again for your contribution, @Zhouzi!

**Pull request merged**
